[build]
 publish = "public"
 command = "hugo --gc --minify"
 functions = "netlify/functions"

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false